### ISSUE TITLE
ImportError: No module named stock_scraper

### ISSUE THREAD

**Issue by 5y** [realpython/flask-stock-visualizer#8]
Hi @mjhea0 ,
Thanks for cool Tutorial :+1: 
I can't import  stock_scraper lib , in fact i can't find that on Pip package, how i can get this?
Cheers,
rehb

**Comment by mjhea0** [comment]
It's not a Python package. Feel free to update it though to create it.

**Comment by 5y** [comment]
@mjhea0 Sure, i was thinking is a Official package, Thank you.
